#!/bin/sh

. /usr/scripts/common_functions.sh

PIDFILE="${RUN_PATH}/mqtt-control.pid"

if [ ! -f /etc/mqtt.conf ]; then
  echo "You have to configure mqtt first. Please see /etc/mqtt.conf.dist for further instructions"
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ -f $PIDFILE ]; then
    echo "MQTT Control already running";
  else
    . /etc/mqtt.conf
    if [ -z ${AUTODISCOVERY_PREFIX+x} ];
      then echo "MQTT autodiscovery is not enabled";
    else
      echo "MQTT autodiscovery is enabled - now publishing initial configurations";
      /usr/scripts/mqtt-autodiscovery.sh
    fi
    echo "Starting MQTT - Control"
    busybox nohup /usr/scripts/mqtt-control.sh &>/tmp/mqtt.log &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill "$pid" && rm "$PIDFILE"
     killall mosquitto_sub 2>/dev/null
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
